import{a as w,S as b,i as a}from"./assets/vendor-DPp42TVS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const S="51642413-09ec9e4a1ede3d4c71955ca94",v="https://pixabay.com/api/";async function u(r,t){const o={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};try{const{data:s}=await w.get(v,{params:o});return s}catch(s){throw new Error(s.message)}}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more");let q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o.likes}</p>
        <p><b>Views:</b> ${o.views}</p>
        <p><b>Comments:</b> ${o.comments}</p>
        <p><b>Downloads:</b> ${o.downloads}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),q.refresh()}function M(){f.innerHTML=""}function p(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function B(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}const $=document.querySelector(".form"),E=document.querySelector(".load-more");let c="",i=1,d=0;$.addEventListener("submit",P);E.addEventListener("click",O);async function P(r){if(r.preventDefault(),c=r.target.elements.searchQuery.value.trim(),!c){a.error({message:"Please enter a search query!"});return}i=1,M(),L();try{p();const t=await u(c,i);if(g(),t.hits.length===0){a.error({message:"No images found. Try another query."});return}d=t.totalHits,y(t.hits),d>15&&B()}catch{a.error({message:"Something went wrong!"})}}async function O(){i+=1;try{p();const r=await u(c,i);g(),y(r.hits),H();const t=Math.ceil(d/15);i>=t&&(L(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({message:"Something went wrong!"})}}function H(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
