import{a as w,S as v,i as a}from"./assets/vendor-DPp42TVS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const S="51642413-09ec9e4a1ede3d4c71955ca94",q="https://pixabay.com/api/";async function f(r,t){const o={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};try{const{data:n}=await w.get(q,{params:o});return n}catch(n){throw new Error(n.message)}}const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more");let M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const t=r.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o.likes}</p>
        <p><b>Views:</b> ${o.views}</p>
        <p><b>Comments:</b> ${o.comments}</p>
        <p><b>Downloads:</b> ${o.downloads}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",t),M.refresh()}function B(){h.innerHTML=""}function g(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function b(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}const $=document.querySelector(".form"),E=document.querySelector(".load-more");let c="",i=1,u=0;$.addEventListener("submit",P);E.addEventListener("click",O);async function P(r){if(r.preventDefault(),c=r.target.elements.searchQuery.value.trim(),!c){a.error({message:"Please enter a search query!"});return}i=1,B(),d();try{g();const t=await f(c,i);if(t.hits.length===0){a.error({message:"No images found. Try another query."});return}u=t.totalHits,p(t.hits),u>15?b():a.info({message:"We're sorry, but you've reached the end of search results."})}catch{a.error({message:"Something went wrong!"})}finally{L()}}async function O(){i+=1,d();try{g();const r=await f(c,i);p(r.hits),H();const t=Math.ceil(u/15);i>=t?(d(),a.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch{a.error({message:"Something went wrong!"})}finally{L()}}function H(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
